### PR TITLE
Use wait for it to wait for postgres

### PR DESCRIPTION
**Pull request by Bonemind**
My #2 request of yesterday did not actually make the container wait for postgres to start.
This pull request waits for up to 60 seconds until postgres actually shows up.

### CODE REVIEW

**Comment by hexylena** [comment]
I'll be honest, I'm not excited about this patch. This is a lot of code and a huge amount of help text trying to do something pretty straightforward like testing the connection to a postgres server.

I'd be interested in your experiences with pg_isready and how that was failing. For my part, I'll look into this sometime this week hopefully.

**Comment by hexylena** [comment]
Hi @Bonemind,

Ok, I had a chance to look at this. Thank you for making an attempt at solving this issue.

- Still not in favour, it seems extremely overly complex for the simple underlying problem.
- I was mis-using the `timeout` parameter of `pg_isready`, originally I assumed it would simply block for that long. It does not.
- I had failed to update the docker-compose to match the changes I made to run.sh, i.e. the necessary environment variables were not exposed https://github.com/erasche/docker-postgraphql/commit/6179fff858dbc810eddf9ab9424c33e07411b085
- Lastly, I believe that a very terse while loop accomplishes the same goal as wait-for-it. https://github.com/erasche/docker-postgraphql/commit/319f148affbfed196ca670e575e83bc22620ba0d Or are there other features from wait-for-it that you need?

**Comment by Bonemind** [comment]
Sorry, got swamped at work so the reply took me a while.

I agree, wait-for-it is overkill, I realized that about 8 hours after pushing this and a while loop would probably do. Tunnel vision and all that.
My issue was just pg_isready not waiting. That's the only thing wait-for-it is doing.

**Comment by hexylena** [comment]
No worries, happens to me too (work / tunnel vision)! Thanks again for the contributions, I really appreciate it. I wouldn't have noticed this bug until it bit me in the ass later.

**Pull request closed without merging**
